version: '2.2'
services:
  friendly-umbrella:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    container_name: server1
    environment:
      - cluster.name=friendly-umbrella
      - node.name=friendly-umbrella
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - es_net

networks:
  es_net:
